// Generated Data Model

export struct AppData {
    temperature: float,
    humidity: float,
    pressure: float,
    wind-speed: float,
    wind-direction: string,
    temp-trend: string,
    humidity-trend: string,
    pressure-trend: string,
    sensor-status: string,
    logger-status: string,
    weather-history: string,
    temp-unit: string,
    pressure-unit: string,
    wind-unit: string,
    logging-interval: float,
    data-retention: float,
    version: string,
}
